5   CLS
10  PRINT
20  PRINT "                       *********************"
30  PRINT "                       * ENGLISCH-PROGRAMM *"
40  PRINT "                       *********************"
50  PRINT
60  PRINT
65  COLOR 2
70  PRINT
80  PRINT "                  UNIT 1  =  1      UNIT 6  =  6"
90  PRINT "                  UNIT 2  =  2      UNIT 7  =  7"
100 PRINT "                  UNIT 3  =  3      UNIT 8  =  8"
110 PRINT "                  UNIT 4  =  4      UNIT 9  =  9"
120 PRINT "                  UNIT 5  =  5      UNIT 10 = 10"
125 PRINT "                         ZUM AUFH™REN 11"
130 COLOR 7
140 INPUT "TIPPE EINE ZAHL"; C
150 ON C GOTO 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000


