100 CLS
110 COLOR 3
120 PRINT
130 PRINT "                               TIC TAC TOE"
140 COLOR 1
150 PRINT
160 PRINT TAB(16); "             "; CHR$(186); "              "; CHR$(186)
170 PRINT TAB(16); "  XX      XX "; CHR$(186); "    OOOOOO    "; CHR$(186); "   OOOOOO"
180 PRINT TAB(16); "    XX  XX   "; CHR$(186); "  OO      OO  "; CHR$(186); " OO      OO"
190 PRINT TAB(16); "      XX     "; CHR$(186); "  OO      OO  "; CHR$(186); " OO      OO"
200 PRINT TAB(16); "    XX  XX   "; CHR$(186); "  OO      OO  "; CHR$(186); " OO      OO"
210 PRINT TAB(16); "  XX      XX "; CHR$(186); "    OOOOOO    "; CHR$(186); "   OOOOOO"
220 PRINT TAB(16); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(206); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(206); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205)
230 PRINT TAB(16); "             "; CHR$(186); "  XX      XX  "; CHR$(186)
240 PRINT TAB(16); "             "; CHR$(186); "    XX  XX    "; CHR$(186)
250 PRINT TAB(16); "             "; CHR$(186); "      XX      "; CHR$(186)
260 PRINT TAB(16); "             "; CHR$(186); "    XX  XX    "; CHR$(186)
270 PRINT TAB(16); "             "; CHR$(186); "  XX      XX  "; CHR$(186)
280 PRINT TAB(16); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(206); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(206); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205); CHR$(205)
290 PRINT TAB(16); "             "; CHR$(186); "              "; CHR$(186); " XX      XX"
300 PRINT TAB(16); "             "; CHR$(186); "              "; CHR$(186); "   XX  XX"
310 PRINT TAB(16); "             "; CHR$(186); "              "; CHR$(186); "     XX"
320 PRINT TAB(16); "             "; CHR$(186); "              "; CHR$(186); "   XX  XX"
330 PRINT TAB(16); "             "; CHR$(186); "              "; CHR$(186); " XX      XX"
340 PRINT TAB(16); "             "; CHR$(186); "              "; CHR$(186)
350 COLOR 3
360 PRINT
370 PRINT "                       EIN SPIEL VON DANIEL EGGER"

